### ISSUE TITLE
Stop saying Hello everytime

### ISSUE THREAD

**Issue by arthurmadecprevost** [mindsers/sanpe-bot#12]
Bot should stop saying Hello to everyone's message containing "hey", "hello".

It should say Hello only to people who say hello without mentioning other people:

_Examples:_

**- "hi @maevatravelandfood" should not receive a response.**
**- "hey" or "hello @SanpeBot" should receive a response.**

**Comment by mindsers** [comment]
Closed by 6cd77cb14cfe0e5a56ebd0522cf195378a24851a
